# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Scientific Machine Learning for Engineers
author: N. Adams, L. Paehler, A. Toshev
copyright: "2022"  # later "2022,2023"
logo: logo.png
exclude_patterns: [_build, venv, data, README.md]

launch_buttons:
  colab_url: https://colab.research.google.com
  binderhub_url: "" # without this line the default is not empty

# Do not force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off # force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/arturtoshev/SciML22-23  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)
  # path_to_book: docs  # Optional path to your book, relative to the repository root

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# parse:
#   myst_enable_extensions:
#     - html_image

# to expand embedded files, i.e. sections. Reference:
# https://github.com/executablebooks/jupyter-book/issues/1134
sphinx:
  config:
    html_theme_options:
      show_navbar_depth: 2